import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/constants/app_strings.dart';
import 'core/routing/app_router.dart';
import 'core/theme/app_theme.dart';
import 'presentation/providers/service_providers.dart';
// Generated by `flutterfire configure` — run that command once the
// Firebase project is created, which will produce this file.
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase is initialized here so Firestore/Auth/FCM are ready before
  // any screen tries to use them. Uncomment `options:` once
  // `firebase_options.dart` has been generated for this project via
  // `flutterfire configure`.
  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );

  // A single ProviderContainer is created up front (rather than letting
  // ProviderScope create its own) so we can kick off notification setup
  // — requesting permission and subscribing to the announcements topic —
  // before the first frame, while still sharing the exact same provider
  // instances with the widget tree via UncontrolledProviderScope below.
  final container = ProviderContainer();

  unawaited(
    container.read(notificationServiceProvider).initialize().catchError((Object error) {
      // Notification setup failing (e.g. permission denied, no Google
      // Play Services) should never block the rest of the app.
      if (kDebugMode) debugPrint('Notification setup failed: $error');
    }),
  );

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const KmcNavigatorApp(),
    ),
  );
}

/// Root widget of KMC Navigator.
class KmcNavigatorApp extends ConsumerWidget {
  const KmcNavigatorApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: AppStrings.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      routerConfig: router,
    );
  }
}
